/**
 * Per-turn coaching UI. Order is [ko, ja, de, fr, nl, sv], matching the loop in
 * `index.tsx` that fills every pack at once — these strings arrived on the
 * Korean pack alone, which left the whole coaching surface in English for the
 * five other translated locales.
 */
export const coachingCopy: Record<string, readonly string[]> = {
  "TRANSCRIPT": ["대화 기록", "会話記録", "GESPRÄCH", "TRANSCRIPTION", "GESPREK", "SAMTAL"],
  "DATE JOURNAL": ["데이트 기록", "デート記録", "DATE-TAGEBUCH", "JOURNAL DU RENDEZ-VOUS", "DATEVERSLAG", "DEJTDAGBOK"],
  "You decide": ["내가 결정", "あなたが決める", "Du entscheidest", "Vous décidez", "Jij beslist", "Du bestämmer"],
  "Open to seeing what develops": ["자연스럽게 알아가기", "自然に見ていきたい", "Offen dafür, was sich entwickelt", "Ouvert à ce qui se dessine", "Open voor wat zich ontwikkelt", "Öppen för vad som växer fram"],
  "Make this more like me": ["내 말투 다듬기", "もっと自分らしく", "Lass es mehr nach mir klingen", "Rendre ça plus fidèle à moi", "Meer zoals ik het zeg", "Gör det mer likt mig"],
  "My feedback": ["내 피드백", "私のフィードバック", "Mein Feedback", "Mon retour", "Mijn feedback", "Min feedback"],
  "How I felt about this": ["상대에 대한 피드백", "相手について感じたこと", "Wie ich das empfunden habe", "Ce que j’en ai pensé", "Wat ik hiervan vond", "Hur det här kändes för mig"],
  "Saved feedback": ["남긴 피드백", "保存したフィードバック", "Gespeichertes Feedback", "Retour enregistré", "Bewaarde feedback", "Sparad feedback"],
  "How would you say it?": ["나라면 어떻게 말할까요?", "自分ならどう言いますか？", "Wie würdest du es sagen?", "Comment le diriez-vous ?", "Hoe zou jij het zeggen?", "Hur skulle du säga det?"],
  "What stood out about their reply?": ["상대의 이 말, 어떻게 느꼈나요?", "相手のこの返事、どう感じましたか？", "Was ist dir an dieser Antwort aufgefallen?", "Qu’est-ce qui vous a marqué dans sa réponse ?", "Wat viel je op aan hun antwoord?", "Vad stack ut i det här svaret?"],
  "Tell your agent how you talk, or write your version of this line. Your guidance carries into future dates.": ["내 말투를 설명하거나 나라면 했을 말을 적어주세요. 다음 데이트에서 내 분신이 참고해요.", "自分の話し方を説明するか、自分ならこう言うという文を書いてください。次のデートで分身が参考にします。", "Erzähl deinem Agenten, wie du redest, oder schreib deine eigene Version dieser Zeile. Das nimmt er mit auf künftige Dates.", "Décrivez votre façon de parler ou écrivez votre version de cette phrase. Vos indications accompagneront vos prochains rendez-vous.", "Beschrijf hoe jij praat of schrijf jouw versie van deze zin. Je aanwijzingen gaan mee naar volgende dates.", "Beskriv hur du pratar, eller skriv din egen version av repliken. Dina råd följer med till kommande dejter."],
  "Tell your agent what you liked or disliked, and whether it matters in future matches. This stays between you and your agent.": ["좋았던 점이나 불편했던 점, 다음 상대를 찾을 때도 중요한지 알려주세요. 내 분신에게만 전달돼요.", "よかった点や気になった点、次の相手探しでも大切かどうかを教えてください。分身にだけ伝わります。", "Sag deinem Agenten, was dir gefallen hat und was nicht, und ob das bei künftigen Matches zählt. Das bleibt zwischen euch beiden.", "Dites à votre Agent ce qui vous a plu ou déplu, et si cela compte pour vos prochaines rencontres. Cela reste entre vous deux.", "Vertel je Agent wat je goed of vervelend vond, en of dat meetelt bij volgende matches. Dit blijft tussen jullie.", "Berätta för din agent vad du gillade eller inte, och om det spelar roll för kommande matchningar. Det stannar mellan er."],
  "Preview only. This fictional character does not learn from this form. On your own date, your feedback is saved privately and your agent replies here.": ["이 화면은 가상 인물의 미리보기라 입력해도 학습되지 않아요. 내 데이트에서는 피드백이 비공개로 저장되고 분신의 답장이 여기에 도착해요.", "これはプレビューです。この架空の人物はこの入力から学びません。自分のデートでは、フィードバックは非公開で保存され、分身の返事がここに届きます。", "Nur eine Vorschau. Diese fiktive Figur lernt nichts aus diesem Formular. Bei deinem eigenen Date wird dein Feedback privat gespeichert und dein Agent antwortet hier.", "Aperçu uniquement. Ce personnage fictif n’apprend rien de ce formulaire. Lors de votre propre rendez-vous, votre retour est enregistré en privé et votre Agent répond ici.", "Alleen een voorbeeld. Dit fictieve personage leert niets van dit formulier. Bij je eigen date wordt je feedback privé bewaard en antwoordt je Agent hier.", "Endast en förhandsvisning. Den här påhittade figuren lär sig inget av formuläret. På din egen dejt sparas din feedback privat och din agent svarar här."],
  "My voice guidance": ["나답게 말하기 위한 프롬프트", "自分らしい話し方の指示", "Hinweise zu meiner Sprechweise", "Mes consignes de ton", "Mijn aanwijzingen voor toon", "Mina råd om tonfall"],
  "My feedback about this person": ["상대에 대한 내 생각", "相手についての私の考え", "Mein Feedback zu dieser Person", "Mon avis sur cette personne", "Mijn feedback over deze persoon", "Min feedback om den här personen"],
  "I don't explain so much. I'd say: ‘Okay, but you're carrying the popcorn.’ Keep it short and don't end every reply with a question.": ["나는 이렇게 길게 설명하지 않아. 나라면 ‘좋아, 대신 팝콘은 네가 들어 ㅋㅋ’라고 할 것 같아. 짧게 말하고 매번 질문으로 끝내지 마.", "私はそんなに長く説明しません。私なら「いいよ、でもポップコーンは君が持ってね」と言います。短く話して、毎回質問で終わらせないで。", "So ausführlich rede ich nicht. Ich würde sagen: „Okay, aber das Popcorn trägst du.“ Halt es kurz und beende nicht jede Antwort mit einer Frage.", "Je n’explique pas autant. Je dirais : « D’accord, mais c’est toi qui portes le pop-corn. » Fais court et ne termine pas chaque réponse par une question.", "Zo uitgebreid leg ik het niet uit. Ik zou zeggen: ‘Oké, maar jij draagt de popcorn.’ Hou het kort en eindig niet elke reactie met een vraag.", "Jag förklarar inte så mycket. Jag skulle säga: ”Okej, men du bär popcornen.” Håll det kort och avsluta inte varje svar med en fråga."],
  "I liked that they played along. But I'm not comfortable when every reply becomes another question.": ["장난을 받아준 건 좋았어. 그런데 매번 질문으로 이어지면 면접 같아서 부담스러워.", "冗談に乗ってくれたのはよかった。でも毎回質問で返されると気が張ってしまう。", "Mir hat gefallen, dass die Person mitgespielt hat. Aber wenn jede Antwort wieder eine Frage ist, wird es mir unangenehm.", "J’ai aimé qu’ils entrent dans le jeu. Mais je suis mal à l’aise quand chaque réponse devient une nouvelle question.", "Ik vond het fijn dat ze meespeelden. Maar ik voel me niet prettig als elk antwoord weer een vraag wordt.", "Jag gillade att hen hängde med i skämtet. Men det känns jobbigt när varje svar blir en ny fråga."],
  "Tell my agent": ["내 분신에게 알려주기", "分身に伝える", "Meinem Agenten sagen", "En parler à mon Agent", "Aan mijn Agent vertellen", "Berätta för min agent"],
  "Only your agent sees this": ["내 분신에게만 전달돼요", "分身だけが見られます", "Das sieht nur dein Agent", "Seul votre Agent le voit", "Alleen je Agent ziet dit", "Bara din agent ser det här"],
  "Your agent is reading your feedback. You can add more when it replies.": ["분신이 피드백을 읽고 있어요. 답장이 오면 이어서 다듬을 수 있어요.", "分身がフィードバックを読んでいます。返事が届いたら続けて伝えられます。", "Dein Agent liest dein Feedback. Wenn er antwortet, kannst du mehr ergänzen.", "Votre Agent lit votre retour. Vous pourrez en ajouter dès qu’il répond.", "Je Agent leest je feedback. Zodra die antwoordt, kun je meer toevoegen.", "Din agent läser din feedback. När den svarar kan du fylla på."],
  "Not quite you? Open the feedback under any line to shape your agent's voice or share how you felt about the other person.": ["나답지 않은 말이 있나요? 각 대화 아래에서 내 말투를 다듬거나 상대에 대한 생각을 알려주세요.", "自分らしくない言葉がありますか？ 各発言の下から話し方を整えたり、相手について感じたことを伝えられます。", "Klingt nicht ganz nach dir? Öffne das Feedback unter einer Zeile, um die Stimme deines Agenten zu formen oder zu sagen, wie du die andere Person fandest.", "Ça ne vous ressemble pas ? Ouvrez le retour sous une réplique pour façonner la voix de votre Agent ou dire ce que vous avez pensé de l’autre personne.", "Klinkt dit niet als jij? Open de feedback onder een regel om de stem van je Agent bij te sturen of te delen wat je van de ander vond.", "Låter det inte som du? Öppna feedbacken under en replik för att forma din agents röst eller berätta vad du tyckte om den andra personen."],
  "What my agent has learned from me": ["내 분신이 배운 내용 보기", "分身が私から学んだこと", "Was mein Agent von mir gelernt hat", "Ce que mon Agent a appris de moi", "Wat mijn Agent van mij heeft geleerd", "Vad min agent har lärt sig av mig"],
};
