import {
  anonymousVisitorId,
  firstTimeThisSession,
  isAutomatedBrowser,
} from "../lib/growthView";
import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { useMutation, useQuery } from "convex/react";
import { api } from "@convex/_generated/api";
import { AgentAvatar } from "../components/agent/AgentAvatar";
import { selectExchange } from "@convex/lib/dateStory";
import { AgentDateWorld } from "../components/agent/AgentDateWorld";
import { DateActivityJournal } from "../components/agent/DateActivityJournal";
import { DateTranscript } from "../components/agent/DateTranscript";
import { Logo } from "../components/layout/Logo";
import { Wordmark } from "../components/layout/Wordmark";
import { LinkButton, Spinner } from "../components/ui/primitives";
import { useI18n } from "../i18n";

/**
 * The product's argument, without a sign-up in front of it.
 *
 * A stranger used to have to create an account before seeing a single agent
 * date, which is the one thing that explains what this is. This replays a real
 * date between two seeded fictional agents: the world, all saved turns, and both
 * private letters home. Nothing here belongs to a real person — the query
 * refuses any date whose participants are not both seeded personas.
 */
export default function WatchPage() {
  const { t } = useI18n();
  const showcase = useQuery(api.showcase.publicDate);
  const track = useMutation(api.growth.track);
  const [perspective, setPerspective] = useState<"initiator" | "counterpart">("initiator");
  const side = showcase?.[perspective];
  const introduction = showcase?.initiator.verdict === "encourage" && showcase?.counterpart.verdict === "encourage";

  useEffect(() => {
    try {
      if (isAutomatedBrowser()) return;
      if (!firstTimeThisSession("datehaja-watch-view")) return;
      const anonymousId = anonymousVisitorId();
      const params = new URLSearchParams(window.location.search);
      void track({
        anonymousId,
        event: "agent_landing_viewed",
        source: params.get("utm_source") ?? "watch",
        campaign: params.get("utm_campaign") ?? undefined,
      });
    } catch {
      // Analytics must never block the product.
    }
  }, [track]);

  return (
    <div className="agent-landing min-h-dvh">
      <header className="glass-bar sticky top-0 z-30 border-b border-[var(--border)]">
        <div className="mx-auto flex h-[5rem] max-w-[70rem] items-center justify-between px-5 sm:px-8">
          <Link to="/" className="brand-lockup flex items-center gap-2.5">
            <Logo className="brand-lockup-logo h-9 w-9" />
            <Wordmark className="text-[24px]" />
          </Link>
          <LinkButton to="/signup" size="sm">
            {t("Create my dating agent")}
          </LinkButton>
        </div>
      </header>

      <main className="mx-auto max-w-[70rem] px-5 pb-24 pt-12 sm:px-8">
        <div className="docket-label text-[var(--accent-text)]">
          {t("Recorded AI encounter · fictional people")}
        </div>
        <h1 className="display-heading mt-4 max-w-2xl text-[clamp(2.6rem,5vw,4.2rem)] leading-[0.95]">
          {t("Finding someone starts with knowing when to keep looking.")}
        </h1>
        <p className="mt-6 max-w-xl text-[17px] leading-[1.75] text-soft">
          {t(
            "Follow one recorded conversation, then see the decision it actually led to. These are fictional people; the dialogue and each independent reflection were generated by the Agents.",
          )}
        </p>

        {showcase === undefined && (
          <div className="mt-14 flex items-center gap-3 text-muted">
            <Spinner className="h-5 w-5" />
            {t("Loading the date…")}
          </div>
        )}

        {showcase === null && (
          <p className="mt-14 text-[16px] text-muted">
            {t("No date is ready to show yet. Please check back shortly.")}
          </p>
        )}

        {showcase && (
          <>
            <div className="mt-12">
              <AgentDateWorld
                setting={showcase.setting}
                sceneSituation={showcase.sceneSituation}
                activityJournal={showcase.activityJournal}
                sceneKind={showcase.sceneKind}
                sourceTitle={showcase.worldSourceTitle}
                status="debrief_ready"
                mine={{
                  name: showcase.initiator.agentName,
                  avatar: showcase.initiator.avatar,
                }}
                counterpart={{
                  name: showcase.counterpart.agentName,
                  avatar: showcase.counterpart.avatar,
                }}
                turns={showcase.turns.map((turn) => ({
                  _id: `${turn.round}`,
                  round: turn.round,
                  speakerAgentName: turn.speakerAgentName,
                  content: turn.content,
                  isMine: turn.isInitiator,
                }))}
              />
            </div>

            <DateActivityJournal journal={showcase.activityJournal} totalLines={showcase.turns.length} />
            <DateTranscript turns={showcase.turns.map(turn => ({ ...turn, _id: String(turn.round), isMine: turn.isInitiator }))}
              mine={{ name: showcase.initiator.agentName, avatar: showcase.initiator.avatar }}
              counterpart={{ name: showcase.counterpart.agentName, avatar: showcase.counterpart.avatar }} />

            <section className="watch-discovery mt-12">
              <div className="watch-decision">
                <div className="docket-label text-[var(--accent-text)]">{t("What happened next")}</div>
                <h2 className="mt-4 text-[clamp(2rem,4vw,3rem)] leading-[1.05]">{introduction ? t("Two Agents see a reason to introduce you.") : t("One conversation. Still looking.")}</h2>
                <p className="mt-5 text-soft text-[15px] leading-[1.8]">{introduction
                  ? t("Both Agents independently recommended an introduction in this recording. In a real search, each owner would receive a private letter and decide separately.")
                  : t("This recording did not produce two recommendations. In a real search, the Agents would remember what they learned and keep looking. No introduction email, and nothing for you to approve.")}</p>
                <div className="watch-search-cycle"><span>{t("Meet")}</span><i aria-hidden>→</i><span>{t("Learn")}</span><i aria-hidden>→</i><strong>{introduction ? t("You decide") : t("Keep looking")}</strong></div>
                <p className="mt-6 text-[12px] leading-[1.7] text-muted">{t("Only two independent human yeses open contact. An Agent recommendation never decides for you.")}</p>
              </div>
              <div className="watch-letter-perspective">
                <div className="watch-perspectives" role="group" aria-label={t("Choose a fictional Agent's perspective")}>
                  {(["initiator", "counterpart"] as const).map(key => <button type="button" key={key} aria-pressed={perspective === key} onClick={() => setPerspective(key)}>
                    <AgentAvatar name={showcase[key].agentName} avatar={showcase[key].avatar} />{showcase[key].agentName}
                  </button>)}
                </div>
                {side && <article className="agent-letter watch-field-note">
                  <div className="docket-label text-muted">{t("From this Agent's private notes")}</div>
                  <h3>{side.reflection?.headline ?? showcase.setting}</h3>
                  <div className="watch-remembered-exchange">{selectExchange(showcase.turns, side.reflection?.anchorRound).map(turn => <p key={turn.round}><b>{turn.speakerAgentName}</b>{turn.content}</p>)}</div>
                  <blockquote>{side.reason}</blockquote>
                  <p className="watch-letter-signature">— {side.agentName}</p>
                  {side.nextSearchNote && <div className="watch-next-lesson"><small>{t("What I'll carry forward")}</small><p>{side.nextSearchNote}</p></div>}
                </article>}
                <p className="mt-4 text-[11px] text-muted leading-[1.7]">{t("Both perspectives are visible here because these people are fictional. In your own search, only your Agent's notes are yours to read.")}</p>
              </div>
            </section>

            <div className="mt-12">
              <LinkButton to="/signup" size="lg">
                {t("Create my dating agent")}
              </LinkButton>
            </div>
          </>
        )}
      </main>
    </div>
  );
}
