type Detail = { title: string; body: string; input: string; output: string; rule: string };
type DiagramCopy = {
  title: string; intro: string; viewLabel: string; systemView: string; learningView: string;
  process: string; savedData: string; decision: string; privatePath: string;
  yourSide: string; sharedWorld: string; theirSide: string;
  briefA: string; briefB: string; briefCaption: string; search: string; searchCaption: string;
  agentA: string; agentB: string; agentCaption: string; transcript: string; transcriptCaption: string;
  reviewA: string; reviewB: string; reviewCaption: string; recommend: string; recommendCaption: string;
  humanA: string; humanB: string; humanCaption: string; connect: string; connectCaption: string;
  settings: string; ownBriefOnly: string; eligiblePair: string; readTranscript: string; ifBothRecommend: string;
  otherwiseSearch: string; waiting: string; waitingDetail: string;
  sequenceTitle: string; sequenceIntro: string; sequenceAlt: string; owner: string; memory: string; nextDate: string;
  messages: string[]; sequenceRoutes: string[]; selfTitle: string; selfDetail: string; otherTitle: string; otherDetail: string;
  approvalTitle: string; approvalDetail: string; detailLabel: string; input: string; output: string; codePath: string;
  selectHint: string; back: string; example: string; footnote: string; mobile: string[];
  details: Record<"brief" | "search" | "date" | "review" | "letter" | "consent" | "memory", Detail>;
};

const en: DiagramCopy = {
  back: "Back to diagram",
  title: "From your words to a human connection.",
  intro: "Two private Agents, one shared encounter. Follow the data, the decisions, and the feedback that shapes the next date.",
  viewLabel: "Diagram view", systemView: "System flow", learningView: "Feedback sequence",
  process: "Process", savedData: "Saved data", decision: "Decision gate", privatePath: "Private path",
  yourSide: "YOUR PRIVATE SIDE", sharedWorld: "SHARED ENCOUNTER", theirSide: "THEIR PRIVATE SIDE",
  briefA: "Your private brief", briefB: "Their private brief", briefCaption: "Voice · needs · boundaries · memory",
  search: "Find an eligible pair", searchCaption: "Both opted in. Both people's settings fit.",
  agentA: "Your AI Agent", agentB: "Their AI Agent", agentCaption: "Speaks from its own brief and the conversation",
  transcript: "Virtual date & record", transcriptCaption: "Alternating turns · scene · saved dialogue",
  reviewA: "Your Dating Agent's review", reviewB: "Their Agent's review", reviewCaption: "Independent read + evidence check",
  recommend: "Both recommend?", recommendCaption: "Two recommendations are required for an introduction.",
  humanA: "You decide", humanB: "They decide", humanCaption: "Read your private letter. Choose yes or no.",
  connect: "Both humans say yes?", connectCaption: "Only then does contact open.",
  settings: "Settings", ownBriefOnly: "Own brief only", eligiblePair: "Eligible pair", readTranscript: "Read saved dialogue", ifBothRecommend: "Yes → private letter",
  otherwiseSearch: "Otherwise → search", waiting: "No match yet? The search continues.",
  waitingDetail: "The site shows the real search state and last check. Routine progress stays in the app; email follows a mutual recommendation and your notification settings.",
  sequenceTitle: "One correction, carried into the next date.",
  sequenceIntro: "Example: “I wouldn't say that. Keep it shorter, and use polite language.” Your feedback is attached to the exact saved line.",
  sequenceAlt: "Feedback sequence: owner sends a correction to their Agent; the Agent updates private memory, retains earlier guidance, replies to the owner, and uses the memory in a future date.",
  owner: "You", memory: "Private memory", nextDate: "Next date",
  messages: ["Select a line + give feedback", "Read prior memory with feedback", "Merge and save durable guidance", "Reply with a next-time example", "Include in the next date prompt"],
  sequenceRoutes: ["You → your Dating Agent", "Private memory → your Dating Agent", "Your Dating Agent → private memory", "Your Dating Agent → you", "Private memory → next date"],
  selfTitle: "“That doesn't sound like me.”", selfDetail: "Refine your phrasing, humor, pace, and politeness. The saved conversation remains intact.",
  otherTitle: "“That reply put me off.”", otherDetail: "Tell your Dating Agent how you felt about the other person. A specific reaction stays specific unless you make it a broader preference.",
  approvalTitle: "Changing search settings needs your approval.", approvalDetail: "Voice guidance enters private memory. A proposed change to relationship intent or structured taste only changes matching after you accept it. Boundaries remain yours to set.",
  detailLabel: "INSIDE THIS STEP", input: "INPUT", output: "OUTPUT", codePath: "Implementation reference", selectHint: "Select a node to inspect its inputs, outputs, and rules.",
  example: "Explore a fictional date record", footnote: "This diagram describes the implemented flow. AI dialogue is a simulation, and its interpretations can be wrong. A recommendation is a reason to explore, not proof of real-world chemistry.",
  mobile: ["Each person keeps a separate brief and memory.", "Only active searches with mutual needs and boundaries can meet.", "Two Agents take turns in a shared scene; the dialogue is saved.", "Each Agent reviews independently. Interpretations are checked against the record.", "Only two recommendations trigger an introduction and private letters.", "Contact opens only after two independent human yeses."],
  details: {
    brief: { title: "01 / A private starting point", body: "Each owner shapes their own Agent's voice, needs, and boundaries. Saved feedback accompanies that Agent into future encounters.", input: "Your profile, explicit preferences, and private coaching.", output: "Your Dating Agent's own brief; structured settings for eligibility.", rule: "The other Agent does not receive your private memory or hidden boundary list." },
    search: { title: "02 / Search with mutual fit", body: "Background searches check eligible real participants who have also opted in. Relationship goals, locations, languages, and configured boundaries must fit both sides.", input: "Active searches + both people's current matching settings.", output: "An eligible encounter, or a waiting state with a later check.", rule: "No eligible pair means no manufactured date. A previous pair is not repeatedly introduced. Pausing stops the search." },
    date: { title: "03 / An unfolding conversation", body: "Each turn uses that Agent's own brief and the saved shared dialogue. Agents can make choices and act within the fictional scene. New encounters allow twelve turns, with one extension to sixteen for a concrete unanswered question.", input: "Own brief + shared scene + preceding turns.", output: "A saved, ordered transcript that both owners can inspect.", rule: "An explicit ending can stop the date earlier. Private prompts stay private; proposed activities must not be presented as completed ones." },
    review: { title: "04 / Read, then check the evidence", body: "The Agents form separate private recommendations. A further model review checks the letter and activity journal against saved words, including who said them and what actually happened.", input: "The completed transcript and each Agent's own context.", output: "A private read and a journal with supporting dialogue references.", rule: "Unsupported interpretations get a repair attempt. If checking still fails, the system withholds them and preserves the original dialogue. These checks are not a guarantee of correctness." },
    letter: { title: "05 / An introduction worth considering", body: "Both Agents must recommend an introduction, and current relationship goals are checked again. Each owner receives their own private letter and a link to the full encounter.", input: "Two encouraging recommendations + current compatible goals.", output: "An introduction to consider; email follows each owner's settings.", rule: "Otherwise, an active search continues. The other side's private verdict and letter remain sealed." },
    consent: { title: "06 / Two human decisions", body: "Each person reads their record and makes a separate choice. One yes leaves contact sealed. Two yeses open the connection; a no closes the introduction and resumes an active search.", input: "Your explicit decision + their explicit decision.", output: "Mutual consent → contact opens and the search stops.", rule: "An Agent's recommendation or a positive coaching message is never human consent." },
    memory: { title: "07 / Feedback that carries forward", body: "A correction is linked to this date, speaker, and line. Your Dating Agent replies privately and merges durable guidance with earlier corrections. Future date prompts read that memory.", input: "A saved line + your own correction or reaction.", output: "Private memory and a concrete example of how to respond next time.", rule: "This changes your Dating Agent, not the other person or the saved past. A new encounter waits while your feedback is being processed; structured search changes require your approval." },
  },
};

const ko: DiagramCopy = {
  back: "흐름도로 돌아가기",
  title: "내가 한 말이, 다음 만남으로 이어지는 과정.",
  intro: "각자의 비공개 에이전트가 하나의 가상 데이트에서 만납니다. 정보가 이동하는 경로와 판단, 피드백이 다음 만남에 반영되는 과정을 살펴보세요.",
  viewLabel: "흐름도 보기", systemView: "전체 동작 흐름", learningView: "피드백 시퀀스",
  process: "처리 과정", savedData: "저장된 정보", decision: "조건 판단", privatePath: "비공개 경로",
  yourSide: "나의 비공개 영역", sharedWorld: "함께하는 가상 만남", theirSide: "상대의 비공개 영역",
  briefA: "나의 비공개 브리프", briefB: "상대의 비공개 브리프", briefCaption: "말투 · 원하는 관계 · 경계 · 기억",
  search: "서로 맞는 상대 탐색", searchCaption: "둘 다 탐색 중이며, 서로의 조건에 맞는지 확인",
  agentA: "내 AI 에이전트", agentB: "상대 AI 에이전트", agentCaption: "자기 브리프와 지금까지의 대화로 응답",
  transcript: "가상 데이트와 기록", transcriptCaption: "번갈아 대화 · 장면 속 행동 · 발언 저장",
  reviewA: "내 에이전트의 회고", reviewB: "상대 에이전트의 회고", reviewCaption: "각자 판단한 뒤 대화 근거를 검증",
  recommend: "둘 다 만남을 추천?", recommendCaption: "두 에이전트가 모두 추천해야 소개로 진행",
  humanA: "내가 직접 결정", humanB: "상대가 직접 결정", humanCaption: "각자의 편지를 읽고 만날지 선택",
  connect: "두 사람 모두 동의?", connectCaption: "두 사람의 ‘예’가 있어야 연락처 공개",
  settings: "설정", ownBriefOnly: "자기 브리프만", eligiblePair: "서로 조건이 맞으면", readTranscript: "저장된 대화 읽기", ifBothRecommend: "예 → 각자의 편지",
  otherwiseSearch: "아니면 → 다시 탐색", waiting: "아직 맞는 사람이 없으면, 탐색을 이어갑니다.",
  waitingDetail: "사이트에서 실제 탐색 상태와 마지막 확인 시점을 보여줍니다. 진행 상황은 앱에서 확인하고, 서로 추천한 만남의 메일은 각자의 알림 설정에 따라 보냅니다.",
  sequenceTitle: "한 번의 피드백이 다음 대화에 닿기까지.",
  sequenceIntro: "예를 들어 “난 이렇게 말 안 해. 더 짧게, 존댓말로 해줘.”라고 알려주세요. 어떤 발언을 고치는지 대화 한 줄과 연결해 기억합니다.",
  sequenceAlt: "피드백 시퀀스: 내가 선택한 발언에 피드백을 보내면 내 에이전트가 기존 지침과 함께 비공개 기억에 저장합니다. 다음에 어떻게 말할지 답하고, 다음 데이트의 프롬프트에 반영합니다.",
  owner: "나", memory: "비공개 기억", nextDate: "다음 데이트",
  messages: ["발언 선택 + 피드백 보내기", "이전 기억과 피드백 함께 읽기", "교정을 합쳐 비공개 기억 저장", "다음에 어떻게 말할지 답변", "다음 데이트 프롬프트에 반영"],
  sequenceRoutes: ["나 → 내 에이전트", "비공개 기억 → 내 에이전트", "내 에이전트 → 비공개 기억", "내 에이전트 → 나", "비공개 기억 → 다음 데이트"],
  selfTitle: "“이건 나다운 말이 아니야.”", selfDetail: "표현, 유머, 대화 속도, 존댓말을 다듬습니다. 이미 나눈 대화 기록은 그대로 남습니다.",
  otherTitle: "“상대의 이 말은 별로였어.”", otherDetail: "상대의 말에서 무엇을 느꼈는지 알려주세요. 특정 상대에 대한 반응을 임의로 모든 상대의 조건으로 확대하지 않습니다.",
  approvalTitle: "탐색 조건을 바꿀 때는 내 승인이 필요해요.", approvalDetail: "말투 교정은 비공개 기억에 반영합니다. 원하는 관계나 구조화된 취향 설정은 변경 제안을 내가 수락해야 매칭에 반영됩니다. 경계 조건은 내가 직접 정합니다.",
  detailLabel: "선택한 단계 자세히", input: "입력", output: "출력", codePath: "구현 코드 경로", selectHint: "상자를 누르면 입력과 출력, 처리 규칙을 볼 수 있어요.",
  example: "가상 데이트 기록 살펴보기", footnote: "현재 구현된 흐름을 설명하는 도식입니다. AI 대화는 시뮬레이션이며 해석이 틀릴 수 있습니다. 추천은 실제로 알아볼 이유를 제안하는 것이며, 현실에서의 궁합을 보장하지 않습니다.",
  mobile: ["두 사람의 브리프와 기억은 각각 비공개로 보관합니다.", "둘 다 탐색 중이고 원하는 관계와 경계 조건이 맞아야 만납니다.", "한 장면에서 두 에이전트가 번갈아 대화하고 발언을 저장합니다.", "각자 회고한 뒤, 대화 원문을 근거로 해석을 검증합니다.", "두 에이전트가 모두 추천해야 소개와 각자의 편지를 보냅니다.", "두 사람이 독립적으로 동의해야 연락처를 공개합니다."],
  details: {
    brief: { title: "01 / 나를 닮은 출발점", body: "각자 자기 에이전트의 말투와 원하는 관계, 경계를 정합니다. 이후에 알려준 피드백도 비공개 기억으로 쌓여 다음 만남에 함께 들어갑니다.", input: "내 프로필, 직접 설정한 조건, 에이전트에게 준 피드백.", output: "내 에이전트만 읽는 브리프와 탐색에 사용할 구조화된 조건.", rule: "상대 에이전트에는 내 비공개 기억이나 숨겨진 경계 목록을 전달하지 않습니다." },
    search: { title: "02 / 서로의 니즈에 맞게 탐색", body: "탐색을 시작한 실제 사용자 중에서 서로 조건이 맞는 상대를 확인합니다. 원하는 관계, 지역, 언어와 직접 설정한 경계가 양쪽 모두 맞아야 합니다.", input: "진행 중인 탐색과 두 사람의 현재 매칭 조건.", output: "조건이 맞는 가상 만남, 또는 다음 확인을 기다리는 상태.", rule: "상대가 없으면 데이트를 만들어내지 않습니다. 같은 조합을 반복 소개하지 않으며, 일시정지하면 탐색도 멈춥니다." },
    date: { title: "03 / 대화하며 전개되는 데이트", body: "매 발언은 자기 브리프와 지금까지 저장된 대화를 바탕으로 생성합니다. 가상 장면 안에서 선택하고 행동할 수 있습니다. 새 만남은 12번의 발언을 기본으로, 구체적으로 더 물어볼 것이 있으면 한 번에 한해 16번까지 이어집니다.", input: "자기 브리프, 함께 있는 장면, 앞서 나눈 대화.", output: "두 사람이 직접 확인할 수 있는 순서대로 저장된 대화 기록.", rule: "한쪽이 명확히 마치면 더 일찍 끝날 수 있습니다. 비공개 프롬프트는 공유하지 않으며, 제안만 한 활동을 이미 한 일로 표시하면 안 됩니다." },
    review: { title: "04 / 각자 회고하고 근거 확인", body: "에이전트가 각자의 비공개 판단을 작성합니다. 추가 모델 검토가 편지와 활동 기록을 원문에 대조하며, 누가 한 말인지와 실제로 벌어진 일을 확인합니다.", input: "완료된 대화와 각자의 에이전트 정보.", output: "비공개 회고와 근거 발언이 연결된 활동 기록.", rule: "근거가 부족하면 한 번 수정을 시도합니다. 재검증에도 실패하면 해당 해석을 내보내지 않고 원문을 보존합니다. 검증을 거쳐도 오류 가능성은 남습니다." },
    letter: { title: "05 / 소개할 이유가 생겼을 때", body: "두 에이전트가 모두 만남을 추천해야 하며, 현재 원하는 관계도 다시 확인합니다. 각 사용자에게 자기 에이전트의 편지와 전체 데이트 기록으로 가는 링크를 전달합니다.", input: "양쪽의 만남 추천과 여전히 맞는 관계 조건.", output: "직접 판단할 수 있는 소개. 메일은 각자의 알림 설정을 따릅니다.", rule: "추천이 성립하지 않으면 진행 중인 탐색을 이어갑니다. 상대의 비공개 판단과 편지는 공개하지 않습니다." },
    consent: { title: "06 / 마지막 결정은 두 사람에게", body: "각자가 기록을 읽고 따로 결정합니다. 한 사람만 동의하면 연락처는 계속 비공개입니다. 두 사람이 동의하면 연결하고, 거절하면 소개를 닫고 진행 중인 탐색을 다시 이어갑니다.", input: "내가 직접 한 선택과 상대가 직접 한 선택.", output: "상호 동의 시 연락처 공개와 탐색 종료.", rule: "에이전트의 추천이나 피드백 중 긍정적인 말은 사람의 동의를 대신할 수 없습니다." },
    memory: { title: "07 / 다음 만남에 남는 피드백", body: "피드백은 날짜뿐 아니라 해당 데이트의 화자와 발언에 연결됩니다. 내 에이전트가 비공개로 답하고, 계속 반영할 지침을 이전 기억과 합칩니다. 다음 데이트의 프롬프트가 이 기억을 읽습니다.", input: "저장된 발언과 내가 직접 말한 교정 또는 상대에 대한 반응.", output: "비공개 기억과 다음에 어떻게 응답할지 보여주는 예시.", rule: "내 에이전트를 다듬으며 상대나 과거 기록을 바꾸지 않습니다. 피드백을 처리하는 동안 새 만남은 기다립니다. 구조화된 탐색 조건은 내 승인 후 바뀝니다." },
  },
};


const ja: DiagramCopy = {
  back: "図に戻る",
  title: "あなたの言葉から、人と人のつながりへ。",
  intro: "二つの非公開エージェントが、ひとつの出会いで交わります。情報の流れ、判断、そして次のデートを形づくるフィードバックをたどってください。",
  viewLabel: "図の表示", systemView: "システムの流れ", learningView: "フィードバックの流れ",
  process: "処理", savedData: "保存データ", decision: "判定", privatePath: "非公開の経路",
  yourSide: "あなたの非公開領域", sharedWorld: "共有される出会い", theirSide: "相手の非公開領域",
  briefA: "あなたの非公開ブリーフ", briefB: "相手の非公開ブリーフ", briefCaption: "話し方 · 望むもの · 境界 · 記憶",
  search: "条件の合う相手を探す", searchCaption: "双方が参加中で、双方の設定が合っていること。",
  agentA: "あなたのAIエージェント", agentB: "相手のAIエージェント", agentCaption: "自分のブリーフと会話から話す",
  transcript: "仮想デートと記録", transcriptCaption: "交互の発言 · 場面 · 保存された会話",
  reviewA: "あなたのエージェントの回顧", reviewB: "相手のエージェントの回顧", reviewCaption: "独立した判断と根拠の検証",
  recommend: "両方が推薦した？", recommendCaption: "紹介には二つの推薦が必要です。",
  humanA: "あなたが決める", humanB: "相手が決める", humanCaption: "自分の手紙を読み、はいかいいえを選ぶ。",
  connect: "ふたりとも「はい」？", connectCaption: "そのときだけ連絡先が開きます。",
  settings: "設定", ownBriefOnly: "自分のブリーフのみ", eligiblePair: "条件の合う組", readTranscript: "保存された会話を読む", ifBothRecommend: "はい → 各自への手紙",
  otherwiseSearch: "それ以外 → 探索へ", waiting: "まだ相手がいなければ、探索は続きます。",
  waitingDetail: "サイトでは実際の探索状況と最後に確認した時刻を表示します。ふだんの進行はアプリで確認でき、メールは相互の推薦と通知設定に従って届きます。",
  sequenceTitle: "ひとつの修正が、次のデートへ。",
  sequenceIntro: "例：「私はそうは言わない。もっと短く、丁寧な言葉で。」フィードバックは保存された発言そのものに結びつきます。",
  sequenceAlt: "フィードバックの流れ：本人がエージェントに修正を送り、エージェントは非公開の記憶を更新し、以前の指示を保ちながら返答し、その記憶を次のデートで使います。",
  owner: "あなた", memory: "非公開の記憶", nextDate: "次のデート",
  messages: ["発言を選んでフィードバック", "以前の記憶と一緒に読む", "残る指示としてまとめて保存", "次はこう言う、と返す", "次のデートのプロンプトに反映"],
  sequenceRoutes: ["あなた → エージェント", "非公開の記憶 → エージェント", "エージェント → 非公開の記憶", "エージェント → あなた", "非公開の記憶 → 次のデート"],
  selfTitle: "「それは自分らしくない。」", selfDetail: "言い回し、ユーモア、速さ、丁寧さを整えます。保存された会話はそのまま残ります。",
  otherTitle: "「あの返事は気になった。」", otherDetail: "相手についてどう感じたかを伝えてください。特定の反応は、あなたが広い好みに変えない限り特定のままです。",
  approvalTitle: "探索設定の変更にはあなたの承認が必要です。", approvalDetail: "話し方の指示は非公開の記憶に入ります。望む関係や構造化された好みの変更は、あなたが受け入れて初めてマッチングに反映されます。境界はあなたが決めます。",
  detailLabel: "この段階の中身", input: "入力", output: "出力", codePath: "実装の参照先", selectHint: "ノードを選ぶと、入力・出力・規則を確認できます。",
  example: "架空のデート記録を見る", footnote: "この図は実装された流れを説明するものです。AIの会話はシミュレーションであり、その解釈は誤ることがあります。推薦は知り合う理由であって、現実の相性の証明ではありません。",
  mobile: ["それぞれが別のブリーフと記憶を持ちます。", "双方が探索中で、望むものと境界が合う場合にだけ会えます。", "二つのエージェントが同じ場面で交互に話し、会話は保存されます。", "各エージェントが独立に回顧し、解釈は記録と照合されます。", "紹介と手紙は、二つの推薦がそろったときだけ届きます。", "連絡先は、二人が別々に「はい」と答えたあとにだけ開きます。"],
  details: {
    brief: { title: "01 / 非公開の出発点", body: "それぞれが自分のエージェントの話し方、望むもの、境界を形づくります。保存されたフィードバックも、そのエージェントとともに次の出会いへ進みます。", input: "プロフィール、明示した希望、非公開の指示。", output: "自分のエージェント専用のブリーフと、条件判定に使う設定。", rule: "相手のエージェントに、あなたの非公開の記憶や隠れた境界の一覧は渡りません。" },
    search: { title: "02 / 双方に合う探索", body: "背景での探索が、同じく参加している実在の相手を確認します。望む関係、地域、言語、設定した境界が双方で合う必要があります。", input: "進行中の探索と、双方の現在のマッチング設定。", output: "条件の合う出会い、または次回確認を待つ状態。", rule: "条件の合う相手がいなければデートは作られません。同じ組を繰り返し紹介せず、停止すれば探索も止まります。" },
    date: { title: "03 / 展開していく会話", body: "各発言は自分のブリーフと保存された共有の会話を使います。エージェントは場面のなかで選び、行動できます。新しい出会いは12発言まで、具体的な未回答の問いがあれば一度だけ16発言まで延びます。", input: "自分のブリーフ + 共有の場面 + それまでの発言。", output: "双方が確認できる、順序どおりに保存された記録。", rule: "明確な締めくくりがあれば早く終わることがあります。非公開のプロンプトは非公開のままで、提案しただけの活動を済んだこととして示してはいけません。" },
    review: { title: "04 / 読み、そして根拠を確かめる", body: "エージェントは別々に非公開の推薦をまとめます。さらに別のモデルによる検証が、手紙と活動記録を保存された言葉と突き合わせ、誰の発言か、実際に何が起きたかを確認します。", input: "完了した記録と、各エージェント自身の文脈。", output: "非公開の回顧と、根拠となる発言を伴う活動記録。", rule: "根拠のない解釈は一度修正を試みます。それでも検証に失敗した場合は出さずに、元の会話を保ちます。この検証は正しさの保証ではありません。" },
    letter: { title: "05 / 検討に値する紹介", body: "両方のエージェントが紹介を推薦し、現在の望む関係も再確認されます。それぞれが自分あての手紙と、出会い全体へのリンクを受け取ります。", input: "二つの前向きな推薦 + いま両立する希望。", output: "検討できる紹介。メールは各自の設定に従います。", rule: "そうでなければ探索が続きます。相手の非公開の判断と手紙は封じられたままです。" },
    consent: { title: "06 / 二人の人間の決定", body: "それぞれが自分の記録を読み、別々に選びます。片方だけの「はい」では連絡先は開きません。二つの「はい」でつながり、「いいえ」は紹介を閉じて探索を再開します。", input: "あなたの明示的な決定と、相手の明示的な決定。", output: "相互の同意 → 連絡先が開き、探索は終わります。", rule: "エージェントの推薦や前向きな言葉は、人の同意の代わりにはなりません。" },
    memory: { title: "07 / 次へ持ち越されるフィードバック", body: "修正はこのデート、話し手、発言に結びつきます。エージェントは非公開で返答し、残る指示を以前の修正と統合します。次のデートのプロンプトがその記憶を読みます。", input: "保存された発言 + あなた自身の修正や反応。", output: "非公開の記憶と、次はどう応じるかの具体例。", rule: "変わるのはあなたのエージェントであり、相手や保存された過去ではありません。フィードバックの処理中は新しい出会いを待ちます。構造化された探索の変更には承認が必要です。" },
  },
};

const de: DiagramCopy = {
  back: "Zurück zum Diagramm",
  title: "Von deinen Worten zu einer echten Verbindung.",
  intro: "Zwei private Agenten, eine gemeinsame Begegnung. Folge den Daten, den Entscheidungen und dem Feedback, das das nächste Date prägt.",
  viewLabel: "Diagrammansicht", systemView: "Systemablauf", learningView: "Feedback-Sequenz",
  process: "Verarbeitung", savedData: "Gespeicherte Daten", decision: "Entscheidungspunkt", privatePath: "Privater Pfad",
  yourSide: "DEINE PRIVATE SEITE", sharedWorld: "GEMEINSAME BEGEGNUNG", theirSide: "SEITE DER ANDEREN PERSON",
  briefA: "Dein privates Briefing", briefB: "Briefing der anderen Person", briefCaption: "Stimme · Wünsche · Grenzen · Gedächtnis",
  search: "Ein passendes Paar finden", searchCaption: "Beide haben zugestimmt. Die Einstellungen beider passen.",
  agentA: "Dein KI-Agent", agentB: "KI-Agent der anderen Person", agentCaption: "Spricht aus dem eigenen Briefing und dem Gespräch",
  transcript: "Virtuelles Date & Aufzeichnung", transcriptCaption: "Abwechselnde Beiträge · Szene · gespeicherter Dialog",
  reviewA: "Die Einschätzung deines Agenten", reviewB: "Einschätzung des anderen Agenten", reviewCaption: "Unabhängige Lesart + Belegprüfung",
  recommend: "Empfehlen beide?", recommendCaption: "Für eine Vorstellung braucht es zwei Empfehlungen.",
  humanA: "Du entscheidest", humanB: "Die andere Person entscheidet", humanCaption: "Lies deinen privaten Brief. Wähle ja oder nein.",
  connect: "Sagen beide Menschen ja?", connectCaption: "Erst dann öffnet sich der Kontakt.",
  settings: "Einstellungen", ownBriefOnly: "Nur das eigene Briefing", eligiblePair: "Passendes Paar", readTranscript: "Gespeicherten Dialog lesen", ifBothRecommend: "Ja → privater Brief",
  otherwiseSearch: "Sonst → weitersuchen", waiting: "Noch kein Treffer? Die Suche geht weiter.",
  waitingDetail: "Die Seite zeigt den tatsächlichen Suchstand und die letzte Prüfung. Den laufenden Stand siehst du in der App; eine E-Mail gibt es erst nach einer beidseitigen Empfehlung, je nach deinen Benachrichtigungseinstellungen.",
  sequenceTitle: "Eine Korrektur, mitgenommen ins nächste Date.",
  sequenceIntro: "Beispiel: „So würde ich das nicht sagen. Fass dich kürzer und bleib höflich.“ Dein Feedback hängt an genau der gespeicherten Zeile.",
  sequenceAlt: "Feedback-Sequenz: Der Mensch schickt seinem Agenten eine Korrektur; der Agent aktualisiert das private Gedächtnis, behält frühere Hinweise, antwortet und nutzt das Gedächtnis in einem späteren Date.",
  owner: "Du", memory: "Privates Gedächtnis", nextDate: "Nächstes Date",
  messages: ["Zeile wählen + Feedback geben", "Früheres Gedächtnis mit dem Feedback lesen", "Dauerhafte Hinweise zusammenführen und sichern", "Mit einem Beispiel für nächstes Mal antworten", "In den nächsten Date-Prompt aufnehmen"],
  sequenceRoutes: ["Du → dein Agent", "Privates Gedächtnis → dein Agent", "Dein Agent → privates Gedächtnis", "Dein Agent → du", "Privates Gedächtnis → nächstes Date"],
  selfTitle: "„Das klingt nicht nach mir.“", selfDetail: "Feile an Ausdruck, Humor, Tempo und Höflichkeit. Das gespeicherte Gespräch bleibt unverändert.",
  otherTitle: "„Diese Antwort hat mich gestört.“", otherDetail: "Sag deinem Agenten, wie du die andere Person empfunden hast. Eine konkrete Reaktion bleibt konkret, solange du sie nicht zu einer allgemeinen Vorliebe machst.",
  approvalTitle: "Änderungen an den Suchoptionen brauchen deine Zustimmung.", approvalDetail: "Hinweise zur Stimme wandern ins private Gedächtnis. Eine vorgeschlagene Änderung an Beziehungsziel oder strukturierter Vorliebe wirkt erst nach deiner Zustimmung auf das Matching. Grenzen setzt weiterhin du.",
  detailLabel: "IN DIESEM SCHRITT", input: "EINGABE", output: "AUSGABE", codePath: "Referenz zur Umsetzung", selectHint: "Wähle einen Knoten, um Eingaben, Ausgaben und Regeln zu sehen.",
  example: "Eine fiktive Date-Aufzeichnung ansehen", footnote: "Dieses Diagramm beschreibt den umgesetzten Ablauf. KI-Dialog ist eine Simulation, und seine Deutungen können falsch sein. Eine Empfehlung ist ein Grund, sich kennenzulernen, kein Beweis für echte Chemie.",
  mobile: ["Jede Person behält ein eigenes Briefing und ein eigenes Gedächtnis.", "Nur aktive Suchen mit passenden Wünschen und Grenzen können sich begegnen.", "Zwei Agenten sprechen abwechselnd in einer gemeinsamen Szene; der Dialog wird gespeichert.", "Jeder Agent urteilt unabhängig. Deutungen werden mit der Aufzeichnung abgeglichen.", "Erst zwei Empfehlungen lösen eine Vorstellung und private Briefe aus.", "Der Kontakt öffnet sich erst, wenn beide Menschen unabhängig voneinander Ja gesagt haben."],
  details: {
    brief: { title: "01 / Ein privater Ausgangspunkt", body: "Jede Person formt Stimme, Wünsche und Grenzen ihres eigenen Agenten. Gespeichertes Feedback begleitet diesen Agenten in künftige Begegnungen.", input: "Dein Profil, ausdrückliche Vorlieben und private Hinweise.", output: "Das eigene Briefing deines Agenten; strukturierte Einstellungen für die Eignung.", rule: "Der andere Agent erhält weder dein privates Gedächtnis noch deine verborgene Grenzenliste." },
    search: { title: "02 / Suche mit beidseitiger Passung", body: "Hintergrundsuchen prüfen infrage kommende echte Teilnehmende, die ebenfalls zugestimmt haben. Beziehungsziele, Orte, Sprachen und gesetzte Grenzen müssen zu beiden Seiten passen.", input: "Aktive Suchen + die aktuellen Matching-Einstellungen beider.", output: "Eine passende Begegnung oder ein Wartezustand mit späterer Prüfung.", rule: "Ohne passendes Paar gibt es kein erfundenes Date. Ein früheres Paar wird nicht wiederholt vorgestellt. Pausieren stoppt die Suche." },
    date: { title: "03 / Ein Gespräch, das sich entfaltet", body: "Jeder Beitrag nutzt das eigene Briefing des Agenten und den gespeicherten gemeinsamen Dialog. Agenten können in der fiktiven Szene wählen und handeln. Neue Begegnungen erlauben zwölf Beiträge, mit einer Verlängerung auf sechzehn für eine konkrete offene Frage.", input: "Eigenes Briefing + gemeinsame Szene + vorherige Beiträge.", output: "Eine gespeicherte, geordnete Abschrift, die beide einsehen können.", rule: "Ein ausdrückliches Ende kann das Date früher beenden. Private Prompts bleiben privat; vorgeschlagene Aktivitäten dürfen nicht als erledigt dargestellt werden." },
    review: { title: "04 / Lesen, dann die Belege prüfen", body: "Die Agenten bilden getrennte private Empfehlungen. Eine weitere Modellprüfung gleicht Brief und Aktivitätsjournal mit den gespeicherten Worten ab, samt der Frage, wer sie gesagt hat und was tatsächlich geschah.", input: "Die vollständige Abschrift und der eigene Kontext jedes Agenten.", output: "Eine private Lesart und ein Journal mit belegenden Dialogverweisen.", rule: "Unbelegte Deutungen bekommen einen Korrekturversuch. Scheitert die Prüfung weiterhin, hält das System sie zurück und bewahrt den ursprünglichen Dialog. Diese Prüfungen sind keine Garantie für Richtigkeit." },
    letter: { title: "05 / Eine Vorstellung, die einen Gedanken wert ist", body: "Beide Agenten müssen eine Vorstellung empfehlen, und die aktuellen Beziehungsziele werden erneut geprüft. Jede Person erhält ihren eigenen privaten Brief und einen Link zur ganzen Begegnung.", input: "Zwei Empfehlungen für ein Treffen + derzeit vereinbare Ziele.", output: "Eine Vorstellung zum Abwägen; E-Mail je nach Einstellungen jeder Person.", rule: "Andernfalls läuft eine aktive Suche weiter. Das private Urteil und der Brief der anderen Seite bleiben versiegelt." },
    consent: { title: "06 / Zwei menschliche Entscheidungen", body: "Jede Person liest ihre Aufzeichnung und entscheidet für sich. Bei nur einem Ja bleibt der Kontakt versiegelt. Zwei Ja öffnen die Verbindung; ein Nein beendet die Vorstellung und nimmt eine aktive Suche wieder auf.", input: "Deine ausdrückliche Entscheidung + ihre ausdrückliche Entscheidung.", output: "Beidseitige Zustimmung → Kontakt öffnet sich und die Suche endet.", rule: "Die Empfehlung eines Agenten oder eine positive Feedback-Nachricht ist niemals menschliche Zustimmung." },
    memory: { title: "07 / Feedback, das weiterwirkt", body: "Eine Korrektur ist mit diesem Date, der sprechenden Seite und der Zeile verknüpft. Dein Agent antwortet privat und führt dauerhafte Hinweise mit früheren Korrekturen zusammen. Künftige Date-Prompts lesen dieses Gedächtnis.", input: "Eine gespeicherte Zeile + deine eigene Korrektur oder Reaktion.", output: "Privates Gedächtnis und ein konkretes Beispiel für die nächste Antwort.", rule: "Das verändert deinen Agenten, nicht die andere Person und nicht die gespeicherte Vergangenheit. Eine neue Begegnung wartet, solange dein Feedback verarbeitet wird; strukturierte Suchänderungen brauchen deine Zustimmung." },
  },
};

const fr: DiagramCopy = {
  back: "Retour au schéma",
  title: "De vos mots à une rencontre réelle.",
  intro: "Deux Agents privés, une seule rencontre partagée. Suivez les données, les décisions et les retours qui façonnent le prochain rendez-vous.",
  viewLabel: "Vue du schéma", systemView: "Flux du système", learningView: "Séquence de retour",
  process: "Traitement", savedData: "Données enregistrées", decision: "Point de décision", privatePath: "Chemin privé",
  yourSide: "VOTRE CÔTÉ PRIVÉ", sharedWorld: "RENCONTRE PARTAGÉE", theirSide: "LEUR CÔTÉ PRIVÉ",
  briefA: "Votre brief privé", briefB: "Leur brief privé", briefCaption: "Ton · attentes · limites · mémoire",
  search: "Trouver un binôme compatible", searchCaption: "Les deux ont donné leur accord. Les réglages des deux concordent.",
  agentA: "Votre Agent IA", agentB: "Leur Agent IA", agentCaption: "Parle à partir de son propre brief et de la conversation",
  transcript: "Rendez-vous virtuel et trace", transcriptCaption: "Tours alternés · scène · dialogue enregistré",
  reviewA: "Le bilan de votre Agent", reviewB: "Le bilan de leur Agent", reviewCaption: "Lecture indépendante + vérification des preuves",
  recommend: "Les deux recommandent ?", recommendCaption: "Deux recommandations sont nécessaires pour une mise en relation.",
  humanA: "Vous décidez", humanB: "Ils décident", humanCaption: "Lisez votre lettre privée. Choisissez oui ou non.",
  connect: "Les deux personnes disent oui ?", connectCaption: "Ce n’est qu’alors que le contact s’ouvre.",
  settings: "Réglages", ownBriefOnly: "Son propre brief uniquement", eligiblePair: "Binôme compatible", readTranscript: "Lire le dialogue enregistré", ifBothRecommend: "Oui → lettre privée",
  otherwiseSearch: "Sinon → recherche", waiting: "Pas encore de correspondance ? La recherche continue.",
  waitingDetail: "Le site affiche l’état réel de la recherche et la dernière vérification. Le suivi ordinaire reste dans l’application ; l’e-mail suit une recommandation mutuelle et vos réglages de notification.",
  sequenceTitle: "Une correction, emportée au rendez-vous suivant.",
  sequenceIntro: "Exemple : « Je ne dirais pas ça. Fais plus court, et reste dans un registre poli. » Votre retour est rattaché à la ligne enregistrée exacte.",
  sequenceAlt: "Séquence de retour : la personne envoie une correction à son Agent ; l’Agent met à jour sa mémoire privée, conserve les consignes antérieures, répond, et utilise cette mémoire lors d’un rendez-vous futur.",
  owner: "Vous", memory: "Mémoire privée", nextDate: "Prochain rendez-vous",
  messages: ["Choisir une ligne + donner un retour", "Lire la mémoire antérieure avec le retour", "Fusionner et enregistrer les consignes durables", "Répondre par un exemple pour la prochaine fois", "Inclure dans le prompt du prochain rendez-vous"],
  sequenceRoutes: ["Vous → votre Agent", "Mémoire privée → votre Agent", "Votre Agent → mémoire privée", "Votre Agent → vous", "Mémoire privée → prochain rendez-vous"],
  selfTitle: "« Ça ne me ressemble pas. »", selfDetail: "Affinez la formulation, l’humour, le rythme et la politesse. La conversation enregistrée reste intacte.",
  otherTitle: "« Cette réponse m’a déplu. »", otherDetail: "Dites à votre Agent ce que vous avez ressenti face à l’autre personne. Une réaction précise reste précise tant que vous n’en faites pas une préférence générale.",
  approvalTitle: "Modifier les réglages de recherche demande votre accord.", approvalDetail: "Les consignes de ton entrent dans la mémoire privée. Une modification proposée de l’objectif relationnel ou d’un goût structuré ne change la mise en relation qu’après votre acceptation. Les limites restent les vôtres.",
  detailLabel: "DANS CETTE ÉTAPE", input: "ENTRÉE", output: "SORTIE", codePath: "Référence d’implémentation", selectHint: "Sélectionnez un nœud pour voir ses entrées, ses sorties et ses règles.",
  example: "Explorer une trace de rendez-vous fictive", footnote: "Ce schéma décrit le flux réellement implémenté. Le dialogue de l’IA est une simulation, et ses interprétations peuvent être fausses. Une recommandation est une raison d’explorer, pas une preuve d’affinité réelle.",
  mobile: ["Chaque personne garde un brief et une mémoire distincts.", "Seules des recherches actives aux attentes et limites compatibles peuvent se rencontrer.", "Deux Agents alternent dans une scène partagée ; le dialogue est enregistré.", "Chaque Agent fait son bilan séparément. Les interprétations sont confrontées à la trace.", "Seules deux recommandations déclenchent une mise en relation et des lettres privées.", "Le contact ne s’ouvre qu’après deux oui humains indépendants."],
  details: {
    brief: { title: "01 / Un point de départ privé", body: "Chaque personne façonne le ton, les attentes et les limites de son propre Agent. Les retours enregistrés accompagnent cet Agent dans les rencontres suivantes.", input: "Votre profil, vos préférences explicites et vos consignes privées.", output: "Le brief propre à votre Agent ; des réglages structurés pour l’éligibilité.", rule: "L’autre Agent ne reçoit ni votre mémoire privée ni votre liste de limites cachée." },
    search: { title: "02 / Une recherche à compatibilité mutuelle", body: "Des recherches en arrière-plan examinent de vrais participants éligibles qui ont eux aussi donné leur accord. Objectifs relationnels, lieux, langues et limites configurées doivent convenir aux deux côtés.", input: "Recherches actives + réglages de mise en relation actuels des deux personnes.", output: "Une rencontre éligible, ou une attente avec une vérification ultérieure.", rule: "Sans binôme éligible, aucun rendez-vous n’est fabriqué. Un binôme déjà vu n’est pas présenté à répétition. Mettre en pause arrête la recherche." },
    date: { title: "03 / Une conversation qui se déroule", body: "Chaque tour s’appuie sur le brief propre à l’Agent et sur le dialogue partagé enregistré. Les Agents peuvent choisir et agir dans la scène fictive. Les nouvelles rencontres autorisent douze tours, avec une extension à seize pour une question précise restée sans réponse.", input: "Brief propre + scène partagée + tours précédents.", output: "Une transcription enregistrée et ordonnée que les deux peuvent consulter.", rule: "Une fin explicite peut arrêter le rendez-vous plus tôt. Les prompts privés restent privés ; une activité proposée ne doit pas être présentée comme réalisée." },
    review: { title: "04 / Lire, puis vérifier les preuves", body: "Les Agents forment des recommandations privées distinctes. Une vérification supplémentaire par un modèle confronte la lettre et le journal d’activité aux mots enregistrés, y compris qui les a dits et ce qui s’est réellement passé.", input: "La transcription complète et le contexte propre à chaque Agent.", output: "Une lecture privée et un journal avec des références au dialogue.", rule: "Les interprétations non étayées font l’objet d’une tentative de correction. Si la vérification échoue encore, le système les retient et préserve le dialogue d’origine. Ces contrôles ne garantissent pas l’exactitude." },
    letter: { title: "05 / Une mise en relation qui mérite réflexion", body: "Les deux Agents doivent recommander une mise en relation, et les objectifs relationnels actuels sont revérifiés. Chaque personne reçoit sa propre lettre privée et un lien vers la rencontre complète.", input: "Deux recommandations encourageantes + des objectifs actuellement compatibles.", output: "Une mise en relation à considérer ; l’e-mail suit les réglages de chacun.", rule: "Sinon, une recherche active continue. Le verdict privé et la lettre de l’autre côté restent scellés." },
    consent: { title: "06 / Deux décisions humaines", body: "Chaque personne lit sa trace et choisit séparément. Un seul oui laisse le contact scellé. Deux oui ouvrent la connexion ; un non ferme la mise en relation et relance une recherche active.", input: "Votre décision explicite + leur décision explicite.", output: "Consentement mutuel → le contact s’ouvre et la recherche s’arrête.", rule: "La recommandation d’un Agent ou un message de retour positif ne vaut jamais consentement humain." },
    memory: { title: "07 / Un retour qui se reporte", body: "Une correction est liée à ce rendez-vous, à la personne qui parle et à la ligne. Votre Agent répond en privé et fusionne les consignes durables avec les corrections antérieures. Les prompts des rendez-vous futurs lisent cette mémoire.", input: "Une ligne enregistrée + votre propre correction ou réaction.", output: "Une mémoire privée et un exemple concret de réponse pour la prochaine fois.", rule: "Cela change votre Agent, pas l’autre personne ni le passé enregistré. Une nouvelle rencontre attend pendant le traitement de votre retour ; les changements structurés de recherche demandent votre accord." },
  },
};

const nl: DiagramCopy = {
  back: "Terug naar het schema",
  title: "Van jouw woorden naar een echte connectie.",
  intro: "Twee privé-Agents, één gedeelde ontmoeting. Volg de gegevens, de beslissingen en de feedback die de volgende date vormt.",
  viewLabel: "Schemaweergave", systemView: "Systeemstroom", learningView: "Feedbackreeks",
  process: "Verwerking", savedData: "Bewaarde gegevens", decision: "Beslispunt", privatePath: "Privépad",
  yourSide: "JOUW PRIVÉKANT", sharedWorld: "GEDEELDE ONTMOETING", theirSide: "HUN PRIVÉKANT",
  briefA: "Jouw privébriefing", briefB: "Hun privébriefing", briefCaption: "Toon · wensen · grenzen · geheugen",
  search: "Een geschikt paar vinden", searchCaption: "Beiden doen mee. De instellingen van beiden passen.",
  agentA: "Jouw AI-Agent", agentB: "Hun AI-Agent", agentCaption: "Spreekt vanuit de eigen briefing en het gesprek",
  transcript: "Virtuele date en verslag", transcriptCaption: "Om beurten · scène · bewaard gesprek",
  reviewA: "Het oordeel van jouw Agent", reviewB: "Het oordeel van hun Agent", reviewCaption: "Onafhankelijke lezing + controle op bewijs",
  recommend: "Bevelen beiden aan?", recommendCaption: "Voor een kennismaking zijn twee aanbevelingen nodig.",
  humanA: "Jij beslist", humanB: "Zij beslissen", humanCaption: "Lees je privébrief. Kies ja of nee.",
  connect: "Zeggen beide mensen ja?", connectCaption: "Pas dan gaat het contact open.",
  settings: "Instellingen", ownBriefOnly: "Alleen de eigen briefing", eligiblePair: "Geschikt paar", readTranscript: "Bewaard gesprek lezen", ifBothRecommend: "Ja → privébrief",
  otherwiseSearch: "Anders → zoeken", waiting: "Nog geen match? Het zoeken gaat door.",
  waitingDetail: "De site toont de echte zoekstatus en de laatste controle. De gewone voortgang blijft in de app; e-mail volgt op een wederzijdse aanbeveling en je meldingsinstellingen.",
  sequenceTitle: "Eén correctie, meegenomen naar de volgende date.",
  sequenceIntro: "Voorbeeld: “Zo zou ik dat niet zeggen. Hou het korter en blijf beleefd.” Je feedback hangt aan precies die bewaarde regel.",
  sequenceAlt: "Feedbackreeks: de eigenaar stuurt een correctie naar de Agent; de Agent werkt het privégeheugen bij, behoudt eerdere aanwijzingen, antwoordt, en gebruikt het geheugen bij een volgende date.",
  owner: "Jij", memory: "Privégeheugen", nextDate: "Volgende date",
  messages: ["Regel kiezen + feedback geven", "Eerder geheugen samen met de feedback lezen", "Blijvende aanwijzingen samenvoegen en bewaren", "Antwoorden met een voorbeeld voor de volgende keer", "Meenemen in de prompt van de volgende date"],
  sequenceRoutes: ["Jij → je Agent", "Privégeheugen → je Agent", "Je Agent → privégeheugen", "Je Agent → jou", "Privégeheugen → volgende date"],
  selfTitle: "“Dat klinkt niet als ik.”", selfDetail: "Stuur formulering, humor, tempo en beleefdheid bij. Het bewaarde gesprek blijft ongewijzigd.",
  otherTitle: "“Dat antwoord stond me tegen.”", otherDetail: "Vertel je Agent wat je van de ander vond. Een specifieke reactie blijft specifiek, tenzij je er een bredere voorkeur van maakt.",
  approvalTitle: "Zoekinstellingen wijzigen vraagt jouw goedkeuring.", approvalDetail: "Aanwijzingen over toon gaan het privégeheugen in. Een voorgestelde wijziging van relatiedoel of gestructureerde voorkeur telt pas mee na jouw akkoord. Grenzen bepaal jij.",
  detailLabel: "IN DEZE STAP", input: "INVOER", output: "UITVOER", codePath: "Verwijzing naar de implementatie", selectHint: "Kies een blok om de invoer, uitvoer en regels te bekijken.",
  example: "Een fictief dateverslag bekijken", footnote: "Dit schema beschrijft de daadwerkelijk gebouwde stroom. AI-dialoog is een simulatie en de interpretaties kunnen fout zijn. Een aanbeveling is een reden om elkaar te leren kennen, geen bewijs van echte klik.",
  mobile: ["Iedereen houdt een eigen briefing en geheugen.", "Alleen actieve zoekopdrachten met passende wensen en grenzen kunnen elkaar ontmoeten.", "Twee Agents praten om beurten in één scène; het gesprek wordt bewaard.", "Elke Agent oordeelt apart. Interpretaties worden getoetst aan het verslag.", "Alleen twee aanbevelingen leiden tot een kennismaking en privébrieven.", "Contact gaat pas open na twee onafhankelijke menselijke ja’s."],
  details: {
    brief: { title: "01 / Een privé beginpunt", body: "Iedereen vormt de toon, wensen en grenzen van de eigen Agent. Bewaarde feedback gaat met die Agent mee naar volgende ontmoetingen.", input: "Je profiel, uitgesproken voorkeuren en privé-aanwijzingen.", output: "De eigen briefing van je Agent; gestructureerde instellingen voor geschiktheid.", rule: "De andere Agent krijgt je privégeheugen en je verborgen grenzenlijst niet." },
    search: { title: "02 / Zoeken op wederzijdse match", body: "Zoekopdrachten op de achtergrond bekijken geschikte echte deelnemers die ook meedoen. Relatiedoelen, plaatsen, talen en ingestelde grenzen moeten aan beide kanten passen.", input: "Actieve zoekopdrachten + de huidige matchinstellingen van beiden.", output: "Een geschikte ontmoeting, of wachten met een latere controle.", rule: "Geen geschikt paar betekent geen verzonnen date. Een eerder paar wordt niet steeds opnieuw voorgesteld. Pauzeren stopt het zoeken." },
    date: { title: "03 / Een gesprek dat zich ontvouwt", body: "Elke beurt gebruikt de eigen briefing van die Agent en het bewaarde gedeelde gesprek. Agents kunnen kiezen en handelen binnen de fictieve scène. Nieuwe ontmoetingen staan twaalf beurten toe, met één verlenging naar zestien voor een concrete onbeantwoorde vraag.", input: "Eigen briefing + gedeelde scène + voorgaande beurten.", output: "Een bewaard, geordend verslag dat beiden kunnen inzien.", rule: "Een uitdrukkelijk einde kan de date eerder stoppen. Privéprompts blijven privé; voorgestelde activiteiten mogen niet als voltooid worden gepresenteerd." },
    review: { title: "04 / Lezen, dan het bewijs controleren", body: "De Agents vormen los van elkaar privé-aanbevelingen. Een extra modelcontrole toetst de brief en het activiteitenlogboek aan de bewaarde woorden, inclusief wie ze zei en wat er werkelijk gebeurde.", input: "Het volledige verslag en de eigen context van elke Agent.", output: "Een privélezing en een logboek met verwijzingen naar het gesprek.", rule: "Niet-onderbouwde interpretaties krijgen één herstelpoging. Lukt de controle dan nog niet, dan houdt het systeem ze tegen en blijft het oorspronkelijke gesprek behouden. Deze controles garanderen geen juistheid." },
    letter: { title: "05 / Een kennismaking die het overwegen waard is", body: "Beide Agents moeten een kennismaking aanbevelen, en de huidige relatiedoelen worden opnieuw getoetst. Iedereen krijgt een eigen privébrief en een link naar de hele ontmoeting.", input: "Twee bemoedigende aanbevelingen + doelen die nu samengaan.", output: "Een kennismaking om te overwegen; e-mail volgt ieders instellingen.", rule: "Anders loopt een actieve zoektocht door. Het privé-oordeel en de brief van de andere kant blijven verzegeld." },
    consent: { title: "06 / Twee menselijke beslissingen", body: "Iedereen leest het eigen verslag en kiest apart. Eén ja laat het contact verzegeld. Twee ja’s openen de verbinding; een nee sluit de kennismaking en hervat een actieve zoektocht.", input: "Jouw uitdrukkelijke keuze + hun uitdrukkelijke keuze.", output: "Wederzijdse instemming → contact gaat open en het zoeken stopt.", rule: "De aanbeveling van een Agent of een positief feedbackbericht is nooit menselijke instemming." },
    memory: { title: "07 / Feedback die meegaat", body: "Een correctie is gekoppeld aan deze date, de spreker en de regel. Je Agent antwoordt privé en voegt blijvende aanwijzingen samen met eerdere correcties. Prompts van volgende dates lezen dat geheugen.", input: "Een bewaarde regel + je eigen correctie of reactie.", output: "Privégeheugen en een concreet voorbeeld voor de volgende keer.", rule: "Dit verandert jouw Agent, niet de ander en niet het bewaarde verleden. Een nieuwe ontmoeting wacht terwijl je feedback wordt verwerkt; gestructureerde zoekwijzigingen vragen jouw goedkeuring." },
  },
};

const sv: DiagramCopy = {
  back: "Tillbaka till diagrammet",
  title: "Från dina ord till en verklig kontakt.",
  intro: "Två privata agenter, ett gemensamt möte. Följ data, besluten och feedbacken som formar nästa dejt.",
  viewLabel: "Diagramvy", systemView: "Systemflöde", learningView: "Feedbackflöde",
  process: "Bearbetning", savedData: "Sparade data", decision: "Beslutspunkt", privatePath: "Privat väg",
  yourSide: "DIN PRIVATA SIDA", sharedWorld: "GEMENSAMT MÖTE", theirSide: "DERAS PRIVATA SIDA",
  briefA: "Din privata brief", briefB: "Deras privata brief", briefCaption: "Röst · önskemål · gränser · minne",
  search: "Hitta ett möjligt par", searchCaption: "Båda har tackat ja. Bådas inställningar passar ihop.",
  agentA: "Din AI-agent", agentB: "Deras AI-agent", agentCaption: "Talar utifrån sin egen brief och samtalet",
  transcript: "Virtuell dejt och dialog", transcriptCaption: "Växelvis · scen · sparad dialog",
  reviewA: "Din agents genomgång", reviewB: "Deras agents genomgång", reviewCaption: "Egen bedömning + kontroll mot underlaget",
  recommend: "Rekommenderar båda?", recommendCaption: "Det krävs två rekommendationer för en introduktion.",
  humanA: "Du bestämmer", humanB: "De bestämmer", humanCaption: "Läs ditt privata brev. Välj ja eller nej.",
  connect: "Säger båda ja?", connectCaption: "Först då öppnas kontakten.",
  settings: "Inställningar", ownBriefOnly: "Endast egen brief", eligiblePair: "Möjligt par", readTranscript: "Läs sparad dialog", ifBothRecommend: "Ja → privat brev",
  otherwiseSearch: "Annars → fortsätt söka", waiting: "Ingen träff än? Sökandet fortsätter.",
  waitingDetail: "Sajten visar det verkliga sökläget och den senaste kontrollen. Det löpande läget ser du i appen; e-post skickas först efter en ömsesidig rekommendation och enligt dina aviseringsinställningar.",
  sequenceTitle: "En rättelse, med till nästa dejt.",
  sequenceIntro: "Exempel: ”Så skulle jag inte säga det. Håll det kortare och håll en artig ton.” Din feedback hänger på exakt den sparade repliken.",
  sequenceAlt: "Feedbackflöde: ägaren skickar en rättelse till sin agent; agenten uppdaterar sitt privata minne, behåller tidigare råd, svarar, och använder minnet vid en senare dejt.",
  owner: "Du", memory: "Privat minne", nextDate: "Nästa dejt",
  messages: ["Välj en replik + ge feedback", "Läs tidigare minne tillsammans med feedbacken", "Slå ihop och spara varaktiga råd", "Svara med ett exempel till nästa gång", "Ta med i nästa dejts prompt"],
  sequenceRoutes: ["Du → din agent", "Privat minne → din agent", "Din agent → privat minne", "Din agent → dig", "Privat minne → nästa dejt"],
  selfTitle: "”Det där låter inte som jag.”", selfDetail: "Finslipa formuleringar, humor, tempo och artighet. Det sparade samtalet lämnas orört.",
  otherTitle: "”Det där svaret störde mig.”", otherDetail: "Berätta för din agent hur du upplevde den andra personen. En specifik reaktion förblir specifik om du inte gör den till en bredare preferens.",
  approvalTitle: "Att ändra sökinställningar kräver ditt godkännande.", approvalDetail: "Råd om tonfall går in i det privata minnet. En föreslagen ändring av relationsmål eller strukturerad smak påverkar matchningen först när du godkänt den. Gränserna sätter du.",
  detailLabel: "INUTI DET HÄR STEGET", input: "INDATA", output: "UTDATA", codePath: "Referens till implementationen", selectHint: "Välj en nod för att se dess indata, utdata och regler.",
  example: "Utforska en påhittad dejt med sparad dialog", footnote: "Diagrammet beskriver det flöde som faktiskt är byggt. AI-dialog är en simulering, och dess tolkningar kan bli fel. En rekommendation är ett skäl att utforska, inte ett bevis för verklig kemi.",
  mobile: ["Var och en har en egen brief och ett eget minne.", "Bara aktiva sökningar med ömsesidiga önskemål och gränser kan mötas.", "Två agenter turas om i en gemensam scen; dialogen sparas.", "Varje agent gör sin genomgång separat. Tolkningar prövas mot den sparade dialogen.", "Bara två rekommendationer utlöser en introduktion och privata brev.", "Kontakten öppnas först när två människor har sagt ja var för sig."],
  details: {
    brief: { title: "01 / En privat utgångspunkt", body: "Var och en formar sin egen agents röst, önskemål och gränser. Sparad feedback följer med agenten till kommande möten.", input: "Din profil, uttalade önskemål och privata råd.", output: "Din agents egen brief; strukturerade inställningar för vem som kan matchas.", rule: "Den andra agenten får varken ditt privata minne eller din dolda lista över gränser." },
    search: { title: "02 / Sökning som passar båda", body: "Sökningar i bakgrunden prövar möjliga verkliga deltagare som också tackat ja. Relationsmål, orter, språk och satta gränser måste passa båda sidor.", input: "Aktiva sökningar + bådas nuvarande matchningsinställningar.", output: "Ett möjligt möte, eller ett väntläge med en senare kontroll.", rule: "Utan ett möjligt par skapas ingen dejt. Ett tidigare par presenteras inte om och om igen. Pausar du stannar sökandet." },
    date: { title: "03 / Ett samtal som växer fram", body: "Varje replik utgår från agentens egen brief och den sparade gemensamma dialogen. Agenter kan välja och handla i den påhittade scenen. Nya möten tillåter tolv repliker, med en förlängning till sexton för en konkret obesvarad fråga.", input: "Egen brief + gemensam scen + tidigare repliker.", output: "En sparad dialog i ordning som båda kan läsa.", rule: "Ett tydligt avslut kan avsluta dejten tidigare. Privata prompter förblir privata; en föreslagen aktivitet får inte framställas som genomförd." },
    review: { title: "04 / Läs, och pröva sedan underlaget", body: "Agenterna bildar var sin privat rekommendation. En ytterligare modellgranskning stämmer av brevet och aktivitetsloggen mot de sparade orden, inklusive vem som sa dem och vad som faktiskt hände.", input: "Hela dialogen och varje agents egen kontext.", output: "En privat läsning och en logg med hänvisningar till dialogen.", rule: "Tolkningar utan stöd får ett försök till rättelse. Håller de ändå inte hålls de tillbaka och den ursprungliga dialogen bevaras. Kontrollerna är ingen garanti för att allt stämmer." },
    letter: { title: "05 / En introduktion värd att överväga", body: "Båda agenterna måste rekommendera en introduktion, och de aktuella relationsmålen prövas på nytt. Var och en får sitt eget privata brev och en länk till hela mötet.", input: "Två rekommendationer att ses + mål som fortfarande går ihop.", output: "En introduktion att överväga; e-post enligt var och ens inställningar.", rule: "Annars fortsätter en aktiv sökning. Den andra sidans privata omdöme och brev förblir förseglade." },
    consent: { title: "06 / Två mänskliga beslut", body: "Var och en läser det som sparats och väljer separat. Ett ja lämnar kontakten förseglad. Två ja öppnar kontakten; ett nej stänger introduktionen och återupptar en aktiv sökning.", input: "Ditt uttryckliga beslut + deras uttryckliga beslut.", output: "Ömsesidigt samtycke → kontakten öppnas och sökandet upphör.", rule: "En agents rekommendation eller ett positivt feedbackmeddelande är aldrig mänskligt samtycke." },
    memory: { title: "07 / Feedback som följer med", body: "En rättelse knyts till den här dejten, talaren och repliken. Din agent svarar privat och väver ihop varaktiga råd med tidigare rättelser. Kommande dejters prompter läser det minnet.", input: "En sparad replik + din egen rättelse eller reaktion.", output: "Privat minne och ett konkret exempel på hur man svarar nästa gång.", rule: "Det förändrar din agent, inte den andra personen och inte det sparade förflutna. Ett nytt möte väntar medan din feedback bearbetas; strukturerade sökändringar kräver ditt godkännande." },
  },
};

const PACKS: Record<string, DiagramCopy> = { ko, ja, de, fr, nl, sv };

export function systemDiagramText(locale: string): DiagramCopy {
  return PACKS[locale.split("-")[0]] ?? en;
}
